# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c154ed251fdeb037c35560435e76f9150fba24d3a386f42198bfb8e45d2f5ec2b31a505357d5bfbf52db39f4a698c48ed4b60e8218022c51de0fcee9eccbd4a

test:
  secret_key_base: efacb0e57b83448d0dfdaac9baf285fb8dfbfc13f36216a95345da3b7f6049707ddf73a5befae8018cb1a6e31dd5b8be670a5494041894de831acd25ddd7d0d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
